version: '2'
services:
    runnerprojetv1-app:
        image: runnerprojetv1
        environment:
        # - _JAVA_OPTIONS=-Xmx512m -Xms256m
        - SPRING_PROFILES_ACTIVE=prod,swagger
        - SPRING_DATASOURCE_URL=jdbc:mysql://runnerprojetv1-mysql:3306/runnerprojetv1?useUnicode=true&characterEncoding=utf8&useSSL=false
        - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        - SPRING_DATA_JEST_URI=http://runnerprojetv1-elasticsearch:9200
        ports:
        - 8080:8080
    runnerprojetv1-mysql:
        extends:
            file: mysql.yml
            service: runnerprojetv1-mysql
    runnerprojetv1-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: runnerprojetv1-elasticsearch
